name: Update DubaiLand Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Toutes les 6 heures
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # Timeout après 3 heures
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Update data
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "🔄 Démarrage de la mise à jour des données..."
        node update-data.js
        echo "✅ Mise à jour terminée"
